version: "3"

vars:
  BUILD_TYPE: '{{default "Debug" .BUILD_TYPE}}'
  BENCHMARKS: '{{default "OFF" .BENCHMARKS}}'

tasks:
  configure:
    cmds:
      - cmake -B build/{{.BUILD_TYPE}} -DCMAKE_BUILD_TYPE={{.BUILD_TYPE}} -DMIRAGE_BUILD_BENCHMARKS={{.BENCHMARKS}} .

  build:
    deps:
      - task: configure
        vars: { BUILD_TYPE: "{{.BUILD_TYPE}}", BENCHMARKS: "{{.BENCHMARKS}}" }
    cmds:
      - cmake --build build/{{.BUILD_TYPE}} --target all

  test:
    vars: { BUILD_TYPE: "Debug" }
    deps: [build]
    cmds:
      - ctest --test-dir build/{{.BUILD_TYPE}}/test --stop-on-failure --output-on-failure

  bench:
    vars: { BUILD_TYPE: "Release", BENCHMARKS: "ON" }
    deps:
      - task: build
        vars: { BUILD_TYPE: "{{.BUILD_TYPE}}", BENCHMARKS: "{{.BENCHMARKS}}" }
    cmds:
      - ./build/{{.BUILD_TYPE}}/test/mirage_math_benchmarks

  clean:
    cmds:
      - rm -rf build

  format:
    desc: Run clang-format on all source files
    cmds:
      - find include test \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -print0 | xargs -0 clang-format -i --verbose

  format-check:
    desc: Check if code is formatted correctly (non-destructive)
    cmds:
      - find include test \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -print0 | xargs -0 clang-format --dry-run -Werror --verbose

  tidy:
    desc: Run clang-tidy static analysis. Treats warnings as errors.
    vars: { BUILD_TYPE: "Debug" }
    deps: [configure]
    cmds:
      - find include \( -name "*.cpp" -o -name "*.hpp" \) -print0 | xargs -0 clang-tidy -p build/{{.BUILD_TYPE}} -fix

  tidy-check:
    desc: Run clang-tidy static analysis. Treats warnings as errors. Try to fix the errors.
    vars: { BUILD_TYPE: "Debug" }
    deps: [configure]
    cmds:
      - find include \( -name "*.cpp" -o -name "*.hpp" \) -print0 | xargs -0 clang-tidy -p build/{{.BUILD_TYPE}}

